name: twilio_pg_video
description: Fork of twilio_programmable_video
version: 1.1.1
homepage: https://github.com/idea-garage/twilio_pg_video
repository: https://github.com/idea-garage/twilio_pg_video
issue_tracker: https://github.com/idea-garage/twilio_pg_video/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  enum_to_string: ^2.0.1
  twilio_programmable_video_platform_interface: ^1.1.0
  twilio_pg_video_web: ^1.15.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.6
  build_runner: ^2.0.1
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: twilio.flutter.twilio_programmable_video
        pluginClass: TwilioProgrammableVideoPlugin
      ios:
        pluginClass: TwilioProgrammableVideoPlugin
      web:
        default_package: twilio_pg_video_web
